language: objective-c
osx_image: xcode7.1
xcode_project: dp_exec_block_on_main_thread.xcodeproj

before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
  - set -o pipefail
  - xcodebuild clean -project dp_exec_block_on_main_thread.xcodeproj -scheme dp_exec_block_on_main_thread-iOS -sdk iphonesimulator | xcpretty -c
  - xcodebuild clean -project dp_exec_block_on_main_thread.xcodeproj -scheme dp_exec_block_on_main_thread-OSX -sdk macosx | xcpretty -c

script:
  - pod lib lint
  - xcodebuild -project dp_exec_block_on_main_thread.xcodeproj -scheme dp_exec_block_on_main_thread-iOS -sdk iphonesimulator | xcpretty -c
  - xcodebuild -project dp_exec_block_on_main_thread.xcodeproj -scheme dp_exec_block_on_main_thread-OSX -sdk macosx | xcpretty -c
